language: R

sudo: false

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

addons:
  apt:
    packages:
      - libxml2-dev

script:
  - Rscript -e 'bookdown::render_book("index.rmd")'
