language: R

sudo: false

cache:
  packages: yes
  directories:
    - $TRAVIS_BUILD_DIR/_bookdown_files

addons:
  apt:
    packages:
      - libxml2-dev

script:
  - Rscript -e "rmarkdown::render_site(encoding = 'UTF-8')"
