# (PART) Présentation des données {-}

# Les variables qualitatives {#variablesqualitatives}

### Mise en place

```{r}
library(tidyverse)
library(questionr)
library(knitr)
```

## Tableau de fréquences

Le tableau de fréquences...

|                                      Titre                                                          ||
|:----------------------:|:--------------------------------:|:----------------------------------------:|
| **Nom de la variable** | **Nombre d'unités statistiques** | **Pourcentage d'unités statistiques**(%) |
|      (_Modalités_)     |      (_Fréquences absolues_)     |         (_Fréquences relatives_)         |
|        **Total**       |                _n_               |                   100%                   |
|                                     _Source_                                                        ||

```{r}
marital <- freq(gss_cat$marital,
                cum = FALSE,
                valid = FALSE,
                total = TRUE)
kable(marital)
```

## Représentation graphique - Le diagramme à bandes

```{r}
ggplot(data = gss_cat, aes(x = marital))+geom_bar()
```

