# (PART) Introduction {-}

# La démarche scientifique {#demarchescientifique}

La démarche scientifique permet d’étudier une problématique de sorte que les résultats obtenus soient valides et reproductibles. 

La démarche scientifique se divise en quatre étapes :

1. Formulation d’un sujet de recherche et méthodologie 
	 - Recherche documentaire
	 - Formulation d’hypothèses
	 - Détermination de la population et/ou de l’échantillon 
1. Collecte des données
1. Traitement des données et analyse des résultats
	 - Présentation des données
	 - Calculs de mesures
	 - Inférence statistique
1. Diffusion des résultats

Le cours de méthodes quantitatives porte entre autres sur les trois premières étapes.

Une fois le sujet de recherche choisi, il faut décider comment la recherche sera menée, c’est-à-dire établir la méthodologie. Pour ce faire, il faut d’abord déterminer s’il est préférable d’effectuer un **recensement** (étude portant sur l’ensemble de la population) ou un **sondage** (étude portant sur une partie de la population).

Il existe des avantages et des inconvénients à faire un recensement.

|:---------------|:--------------------------------------------------------------------------------------------------------------------------|
| Avantages     | Les résultats obtenus correspondent exactement à la réalité. Il est aisé d’analyser des sous-ensembles de la population. |
| Inconvénients | Les coûts sont élevés.Les résultats sont longs à obtenir.                                                                |

Puisqu’il est généralement souhaitable que la récolte d’information soit faite à coûts moindres et le plus rapidement possible, le sondage est souvent utilisé. Ensuite, le chercheur doit définir les éléments suivants : 

|:--------------|:------------------------------------------------------------------------------------------|
| La population |	Ensemble des personnes, faits ou objets sur lesquels porte l’étude.Sa taille est notée $N$. |
| L’unité statistique |	Une personne, fait ou objet de la population. |
| L’échantillon	|	Sous-ensemble de la population utilisé lors d’un sondage. Sa taille est notée $n$. |


Dans le choix de la méthodologie, il est aussi important de déterminer les variables étudiées, le type des variables, les échelles de mesure, les types de questions et les techniques d’échantillonnage. Ceux-ci seront étudiés dans les chapitres suivants.
